<?php

namespace Database\Seeders;

use App\Models\GlcVotingNonVoting;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GlcVotingNonVotingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $members = [
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Arts and Letters',
                'name' => 'EDMEAN JULIUS C. COBILLA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Arts and Letters',
                'name' => 'IHRA MAE C. MADRIDEO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Arts and Letters',
                'name' => 'JENELLE V. PALMA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Arts and Letters',
                'name' => 'CINDY A. GRAYDA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Arts and Letters',
                'name' => 'JESALVA, JUSTINE FRANCESCA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'FRANCINE FAITH V. ANONUEVO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'MICAH MAE BALIDUYA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'DENMARK GIL LEOPARDAS',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'ROXANNE MAE MONTERO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'CLARENZ POSERAN',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'PATRICIA ANNE RICO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'LORENZ A. SAYSON',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'CAMIA MAE LADESMA VERALLO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Detal Medicine',
                'name' => 'HANS KRISTIAN B. CANALES',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Education',
                'name' => 'CHRISTIAN ALCERA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Education',
                'name' => 'JAY MAR BARCENAS',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Education',
                'name' => 'FRANCIS FERHOL BORRAS',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Education',
                'name' => 'JENNY LEE COMPETENTE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Education',
                'name' => 'KATHLEEN JOY LALAGUNA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'KENJHIE R. ALFONOSO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'EVA MICAH ANGELA S. CASIDA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'MARK JOSEPH L. DELAS LLAGAS',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'DARWIN ISIAH L. GUBIA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'TRISTANDOODS L. MELITANTE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'GABRIEL TIMOTHY R. MILLETE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'HANNAH OLIVIA REGOROSO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Engineering',
                'name' => 'MARIEL SOPHIA ROSERO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Industrial Technology',
                'name' => 'KRISTINE JOY Q. ANTEGRA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Industrial Technology',
                'name' => 'EMALENE N. MANUEL',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Industrial Technology',
                'name' => 'MARIANE SIBYL',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Law',
                'name' => 'JAMIESON EMMANUEL DAYAWON',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Law',
                'name' => 'MA. NICOLE VILLA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Law',
                'name' => 'IVY VILLA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Law',
                'name' => 'JESSA MAE BILASON',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Nursing',
                'name' => 'MARY KIMBERLY V. BONTO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Nursing',
                'name' => 'ZANDER B. VOSOTROS',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Science',
                'name' => 'JENNY MAE BUENO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Science',
                'name' => 'CHENIE NIŃA BUERGO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Science',
                'name' => 'JONASENH ANTHONE LAVAPIE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Science',
                'name' => 'SIMON ANGELO KARLO NARVAEZ',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Science',
                'name' => 'ANGELO JOSE RICO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Social Sciences and Philosophy',
                'name' => 'DARIOS JOHN E. ANTONIO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Social Sciences and Philosophy',
                'name' => 'MAREIL C. LIZOR',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Social Sciences and Philosophy',
                'name' => 'IVAN P. ROSERO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Social Sciences and Philosophy',
                'name' => 'JORIEL ALECKS P. CALLEJA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'College of Social Sciences and Philosophy',
                'name' => 'DAVE RUSSELL C. ADVINCULLA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'Institute of Design and Architecture',
                'name' => 'KYLE MIRA NAVARRO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'Institute of Design and Architecture',
                'name' => 'ROJAN PAUL BINAS',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'Institute of Design and Architecture',
                'name' => 'KERWIN AJE CEDENO'
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'Institute of Physical Education, Sports, and Recreation',
                'name' => 'GIAN CARLO L. MORADA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'Institute of Physical Education, Sports, and Recreation',
                'name' => 'JENALYN VERDEFLOR',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'Jesse M. Robredo Institute of Governance and Development',
                'name' => 'JUSTIN DAVID V. REYNOSO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Gubat',
                'name' => 'MARK D. ESTRELLADO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Gubat',
                'name' => 'LEIANE V. BALOYO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'Gubat Campus',
                'name' => 'JAMES RYAN LUNA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Guinobatan',
                'name' => 'JOSIE N. NAZ',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Guinobatan',
                'name' => 'HONEY GRACE L. NOLEAL',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Guinobatan',
                'name' => 'JENESSA D. DIONELA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Tabaco',
                'name' => 'CHRISJON RUPERT B. BONGAT',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Tabaco',
                'name' => 'PRECIOUS YVETTE C. BORAGAY',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Tabaco',
                'name' => 'MARIE KAYE B. MIRALO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Tabaco',
                'name' => 'RUTH S. BELLO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Tabaco',
                'name' => 'APRIL BOBIS',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'SAMANTHA JOY ALCANTARA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'SHARLENE JANE ALCANTARA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'MARK JOSEPH RAÑADA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'JOHN PAUL IMPERIO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'CHRISTIAN REONDANGA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'RONIE BAMBE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'FARIDHA DE LIMA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE REPRESENTATIVES',
                'short' => 'REPRESENTATIVES',
                'college' => 'BU Polangui',
                'name' => 'CHRISTIAN JAKE SOLANO',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Arts and Letters',
                'name' => 'CRUZ, YESHA FAYE B.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'AARON JOAQUIN M. LAZALA',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Dental Medicine',
                'name' => 'LANCE PAJE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Education',
                'name' => 'SHIERALYN M. DE LA TORRE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Engineering',
                'name' => 'HANNAH ERIKA N. MAGAYANES',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Industrial Technology',
                'name' => 'RAZON, JOHN MARK R.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Law',
                'name' => 'LIWANAG, JOSE CRISTOBAL',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Medicine',
                'name' => 'GUZMAN, LOU VINCENT',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Nursing',
                'name' => 'AGUILAR, JETHOR A.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Science',
                'name' => 'BALGEMINO, SARAH',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'College of Social Sciences and Philosophy',
                'name' => 'ESTO, MARCK LESTER B.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'Institute of Design and Architecture',
                'name' => 'DESOLO, HOMER REDEN',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'Institute of Physical Education, Sports, and Recreation',
                'name' => 'LIM, JAMES HAROLD S.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'Jesse M. Robredo Institute of Governance and Development',
                'name' => 'DACIR, JAKE',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'BU Gubat',
                'name' => 'EVA, ANGELINA E.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'BU Guinobatan',
                'name' => 'BELLEN, GWYNETH E.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'BU Polangui',
                'name' => 'SALEM, JHON REY E.',
            ],
            [
                'type' => 'VOTING MEMBERS | COLLEGE STUDENT COUNCIL PRESIDENTS',
                'short' => 'PRESIDENTS',
                'college' => 'BU Tabaco',
                'name' => 'BATALLER, RODEL B.',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Pre-Law Society',
                'name' => 'SHAINE THERESE AGUADO',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Yeshua Heartbeat (YHB)',
                'name' => 'JEMIMA S. UY',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Lawod',
                'name' => 'JOHN NICOLE A. BOLON',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Rise For Education - Bicol University',
                'name' => 'BERMAS, EMMAN',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Order of The Blue Feather Society',
                'name' => 'JAIRUS ALEXIS A. RICO',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Elevate - Bicol University',
                'name' => 'ALLONICA B. BOMBITA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Animal Welfare Society',
                'name' => 'MARIANNE BOS',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Alpha Phi Omega - Gamma Omicron Chapter',
                'name' => 'ANGELO ANDRE CAMATA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Google Developers Student Clubs',
                'name' => 'PELON, JONATHAN',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Quarta BU',
                'name' => 'JORENE JASON DE VERA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'League of Liberal Reformists - Reporma Coalition',
                'name' => 'HANNAH GWENYTH B. COLLASITO',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Every Nation Campus BU',
                'name' => 'ROSEMARIE BAS',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Bicol University Isarog',
                'name' => 'JONATHAN PELON',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Swifties Society',
                'name' => 'MARTUS, JOHN RENIEL',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Bicol University Lakas-Angkan Youth Fellowship',
                'name' => 'JOBERT A. HERNANDEZ',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Debate Society',
                'name' => 'JEARY ROXAS',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'IPOSE BUFS',
                'name' => 'ROMEO D. JACOB JR.',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Pre-Medical Society',
                'name' => 'MORA, MERRYL C.',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Buklod Bicol University',
                'name' => 'MA. BERNADETTE PANALIGAN',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU College Y Club',
                'name' => 'PRINCES ANN B. RUSTE',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU University Based Club for UNESCO',
                'name' => 'ADOR CABALBAG',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU National Service Reserve Corps',
                'name' => 'JASMINE A. PERTEZ',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Cru Bicol University',
                'name' => 'JENNY LOU M. SOLIS',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'AMICUS - BU Chapter',
                'name' => 'HEMERLEE GEM OBADO',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Leaders: League of Democrats',
                'name' => 'CEDRICK B. DELOS SANTOS',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Bantayog',
                'name' => 'GIO ALFONSO VEGA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Aletheian Student Circle',
                'name' => 'JHON DAVE TRINIDAD',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Society of Sorsoganons',
                'name' => 'RICHELLE MAE N. LINGA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Student Commission on Audit',
                'name' => 'ARIANNA KESI DIGO',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'American Concrete Institute Philippines - BU Chapter',
                'name' => 'RICHELLE AYSON MONSALVE',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Bicol University Musika',
                'name' => 'VON HAROLD HERMOSA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'Sonic Society of the Youth',
                'name' => 'LAWRENCE C. HERMOSA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'One Share, One Care Bicol University',
                'name' => 'XANDRALYN MAGDASOC',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Campus Ministry Organization',
                'name' => 'RALPH LAWRENCE DADO',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Integrity Crusaders',
                'name' => 'LUISITO GONZALES JR.',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Red Cross Youth Council',
                'name' => 'KEI ANN LOUISE BALAGASAY',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU BUGKOS',
                'name' => 'JORGE FELIPE ICAMEN',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU SARO',
                'name' => 'CASSANDRA HERVACIO',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Spark',
                'name' => 'JOHN PAUL LLANETA',
            ],
            [
                'type' => 'VOTING MEMBERS | UNIVERSITY-BASED ORGANIZATION PRESIDENTS',
                'short' => 'PRESIDENTS',
                'organization' => 'BU Association of Young Business Leaders and Entrepreneurship',
                'name' => 'GERVY JOHN K. TAMAYO',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Bicol Universitarian',
                'college' => 'University Publication',
                'name' => 'JAMES EDWARD M. TAMBOBONG',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'KROKIS',
                'college' => 'Institute of Design and Architecture',
                'name' => 'ANGELA MARIE B. MAR',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'Budyong',
                'college' => 'College of Arts and Letters',
                'name' => 'KARL IAN MORRISSEY RAMOS',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Vital Signs',
                'college' => 'College of Nursing',
                'name' => 'MC LUIS GLEN ASERDANO',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'CaSSiPi',
                'college' => 'College of Social Sciences and Philosophy',
                'name' => 'JAYSON ENEBRAD',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Inditers',
                'college' => 'BU Polangui',
                'name' => 'LEVI CAAYA III',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Gearcast',
                'college' => 'College of Engineering',
                'name' => 'HUMPRAY O. PASANO',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Probe',
                'college' => 'BU Gubat',
                'name' => 'ERICAH NICOLE E. MORFE',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'Scientia',
                'college' => 'College of Science',
                'name' => 'RAVEN MAE L. CHING',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Mentor',
                'college' => 'College of Education',
                'name' => 'MA. DOROTHY MAE ROJO',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Seedling',
                'college' => 'BU Guinobatan',
                'name' => 'REIH JOHN GRANDE',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Appraiser',
                'college' => 'College of Business, Economics, and Management',
                'name' => 'SHANE ASHLY QUINONES',
            ],
            [
                'type' => 'NON-VOTING MEMBERS | STUDENT PUBLICATIONS’ EDITORS-IN-CHIEF',
                'short' => 'EDITORS-IN-CHIEF',
                'publication' => 'The Olympian',
                'college' => 'Institute of Physical Education, Sports, and Recreation',
                'name' => 'JOSE ALFRED MALAGA',
            ],
        ];


        foreach ($members as $member) {
            GlcVotingNonVoting::create($member);
        }
    }
}
